[project]
name = "regression-lab"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
jupyterlab = ">=4.2.1,<4.3"
scikit-learn = ">=1.5.0,<1.6"
pandas = ">=2.2.2,<2.3"
matplotlib = ">=3.8.4,<3.9"
numpy = ">=1.26.4,<1.27"
seaborn = ">=0.13.2,<0.14"
